/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dcm4che3_openjph_OpenJPH */

#ifndef _Included_org_dcm4che3_openjph_OpenJPH
#define _Included_org_dcm4che3_openjph_OpenJPH
#ifdef __cplusplus
extern "C" {
#endif
#undef org_dcm4che3_openjph_OpenJPH_PROGRESSION_LRCP
#define org_dcm4che3_openjph_OpenJPH_PROGRESSION_LRCP 0L
#undef org_dcm4che3_openjph_OpenJPH_PROGRESSION_RLCP
#define org_dcm4che3_openjph_OpenJPH_PROGRESSION_RLCP 1L
#undef org_dcm4che3_openjph_OpenJPH_PROGRESSION_RPCL
#define org_dcm4che3_openjph_OpenJPH_PROGRESSION_RPCL 2L
#undef org_dcm4che3_openjph_OpenJPH_PROGRESSION_PCRL
#define org_dcm4che3_openjph_OpenJPH_PROGRESSION_PCRL 3L
#undef org_dcm4che3_openjph_OpenJPH_PROGRESSION_CPRL
#define org_dcm4che3_openjph_OpenJPH_PROGRESSION_CPRL 4L
/*
 * Class:     org_dcm4che3_openjph_OpenJPH
 * Method:    encode
 * Signature: ([BIIIIZZFII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_dcm4che3_openjph_OpenJPH_encode
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jboolean, jboolean, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
